spring:
  # 이메일 인증 관련 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: thkim610@gmail.com
    password: klhffwdwthcvelzz
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000






  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://honbabstop.c1vj4mnezxta.us-east-1.rds.amazonaws.com:3306/honbabstopDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useLegacyDatetimeCode=false
    username: root
    password: 12345678

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  messages:
    basename: messages/messages

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: honbab-bucket
    credentials:
      access-key: AKIA2KZERIL2JJ4HOFVL

      secret-key: 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



  # redis 관련 설정
  redis:
    host: localhost
    port: 6379







